include = ["*.py", "*.pyi", "**/pyproject.toml"]
exclude = [
    ".bzr", ".direnv", ".eggs", ".github", ".git-rewrite", ".hg",
    ".ipynb", ".ipynb_checkpoints", ".mypy_cache", ".nox", ".pants.d",
    ".pyenv", ".pytest_cache", ".pytype", ".ruff_cache", ".svn", ".tox",
    ".venv", ".vscode", "__pypackages__", "_build", "buck-out", "build",
    "dist", "node_modules", "site-packages", "venv", "**/migrations",
]

line-length    = 90
indent-width   = 4
target-version = "py312"

[lint]
select = [
    "E", "W", "F", "I", "N", "D", "UP", "B", "SIM", "RET", "ARG", "C90", "RUF",
]
ignore = [
    "N999",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D107",
    "D401",
]

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 10

[lint.isort]
known-third-party = ["enchant", "absl"]
force-single-line = false

[lint.per-file-ignores]
"tests/**/*.py" = ["ARG002", "SIM117", "E501"]

[format]
quote-style               = "double"
indent-style              = "space"
skip-magic-trailing-comma = false
line-ending               = "auto"
