name: CD

on:
  push:
    branches: [main]

jobs:
  jira-guard:
    name: Jira Guard
    permissions:
      pull-requests: read
      contents: read
    uses: byteit-ai/.github/.github/workflows/jira-guard.yml@main
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
