name: Rebase Feature from Sprint

on:
  create:
    branches:
      - "sprint*-*"

permissions:
  contents: write
  
jobs:
  call-rebase-feature-from-sprint:
    uses: byteit-ai/.github/.github/workflows/rebase-feature-from-sprint.core.yml@main
